/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.nora.bird;

import java.util.Random;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {

        String[] rps = {"sten", "påse", "sax"};
        String computerMove = rps[new Random().nextInt(rps.length)];

        Scanner scanner = new Scanner(System.in);
        String playerMove;

        while (true) {
            System.out.println("Please enter your move (sten , påse , sax )");
            playerMove = scanner.nextLine();
            playerMove = playerMove.toLowerCase().trim();
            if (("sten".equalsIgnoreCase(playerMove)) || playerMove.equals("påse") || playerMove.equals("sax")) {
                break;
            }
            System.out.println(playerMove + "försök igen");
        }
        System.out.println("computer played: " + computerMove);

        if (playerMove.equals(computerMove)) {
            System.out.println("avgjort!!!");
            return;
        }

        if (playerMove.equals("sten")) {

            if (computerMove.equals("påse")) {
                System.out.println("Du förlorade!!");
                return;
            }
            System.out.println("Du vann!!");
            return;
        }

        if (playerMove.equals("påse")) {
            if (computerMove.equals("sten")) {
                System.out.println("Du vann!!");
                return;
            }
            System.out.println("Du förlorade!!");
            return;
        }


        if (computerMove.equals("påse")) {
            System.out.println("Du vann!!");
            return;
        }
        System.out.println("Du förlorade!!");
    }
}