/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package se.nora.bird;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        @Test
        public void gameShouldWorkWithLowerCase() {
            String[] args = {"sten"};
            App.main(args);
            assertTrue("Game should end!", true);
        }

        @Test
        public void gameShouldWorkWithUpperCase() {
            String[] args = {"Sten"};
            App.main(args);
            assertTrue("Game should end!", true);
        }

    }
}
